/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./about/**/*.html", "./blog/**/*.html", "./certifications/**/*.html", "./projects/**/*.html", "./resume/**/*.html", "./services/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#ebf1f9",
        "surface-container-highest": "#d5dee7",
        "inverse-surface": "#090f13",
        "surface-bright": "#f2f7fe",
        "on-background": "#2a2f35",
        "on-tertiary": "#f0f2ff",
        "error-dim": "#b92902",
        "primary-fixed": "#ff8a00",
        "on-primary-container": "#442100",
        "on-error": "#ffefec",
        "secondary-fixed-dim": "#00efce",
        "on-primary-fixed-variant": "#512800",
        "on-tertiary-fixed-variant": "#003580",
        "tertiary-dim": "#004aad",
        "surface-dim": "#ccd5df",
        "on-primary-fixed": "#180800",
        "tertiary-fixed-dim": "#77a1ff",
        "surface-container": "#e2e9f1",
        "on-tertiary-fixed": "#00163d",
        "on-secondary-fixed-variant": "#006859",
        "on-surface-variant": "#565c62",
        "tertiary-container": "#8eafff",
        "primary-dim": "#7c4000",
        "on-secondary": "#c2ffef",
        "primary-fixed-dim": "#eb7f00",
        "secondary-dim": "#005a4d",
        "on-error-container": "#520c00",
        "tertiary": "#0055c4",
        "background": "#f2f7fe",
        "secondary": "#006859",
        "on-surface": "#2a2f35",
        "surface-tint": "#8d4a00",
        "tertiary-fixed": "#8eafff",
        "on-secondary-container": "#005d4f",
        "surface-variant": "#d5dee7",
        "error": "#b02500",
        "error-container": "#f95630",
        "primary-container": "#ff8a00",
        "secondary-fixed": "#26fedc",
        "inverse-primary": "#ff8a00",
        "surface-container-high": "#dce3ec",
        "surface": "#f2f7fe",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#00483d",
        "outline-variant": "#a8aeb4",
        "primary": "#8d4a00",
        "inverse-on-surface": "#989da4",
        "outline": "#72777d",
        "on-primary": "#fff0e7",
        "secondary-container": "#26fedc",
        "on-tertiary-container": "#002d6f"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
